In [1]:
import numpy as np 

In [2]:
my_list  = [1,2,3,4,5]
type(np.array(my_list))

numpy.ndarray

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.random.randint(10)

6

In [33]:
np.random.randint(20,50)

23

In [43]:
np.random.randint(0,100,(4,4))

array([[ 4, 48,  6, 15],
       [72, 21, 10, 18],
       [68, 36,  2, 28],
       [13, 98, 27, 67]])

In [51]:
np.random.seed(42)
np.random.randint(0,100,(4,4))

array([[51, 92, 14, 71],
       [60, 20, 82, 86],
       [74, 74, 87, 99],
       [23,  2, 21, 52]])

In [55]:
np.random.seed(101)
arr = np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [56]:
arr.max()

95

In [57]:
arr.min()

9

In [58]:
arr.mean()

60.8

In [59]:
arr.argmax()

0

In [60]:
arr.argmin()

7

In [61]:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [65]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [66]:
mat[0,0]

0

In [67]:
mat[0,:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# Pandas Practice

In [69]:
import pandas as pd

In [71]:
name = ["Munna","Karim","Rahim","Kamal"]
s = pd.Series(name)
s

0    Munna
1    Karim
2    Rahim
3    Kamal
dtype: object

In [72]:
s.values

array(['Munna', 'Karim', 'Rahim', 'Kamal'], dtype=object)

In [73]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [74]:
s.dtype

dtype('O')

In [75]:
price = [4,5,6,8,7,9]

In [77]:
p = pd.Series(price)
p

0    4
1    5
2    6
3    8
4    7
5    9
dtype: int64

In [78]:
p.sum()

39

In [79]:
p.product()

60480

In [80]:
p.mean()

6.5

In [81]:
pd.read_csv("pokemon.csv")

Pokemon     Type
0     Bulbasaur    Grass
1       Ivysaur    Grass
2      Venusaur    Grass
3    Charmander     Fire
4    Charmeleon     Fire
..          ...      ...
716     Yveltal     Dark
717     Zygarde   Dragon
718     Diancie     Rock
719       Hoopa  Psychic
720   Volcanion     Fire

[721 rows x 2 columns]

In [97]:
data = pd.read_csv("pokemon.csv")
data.head()
data

Pokemon     Type
0     Bulbasaur    Grass
1       Ivysaur    Grass
2      Venusaur    Grass
3    Charmander     Fire
4    Charmeleon     Fire
..          ...      ...
716     Yveltal     Dark
717     Zygarde   Dragon
718     Diancie     Rock
719       Hoopa  Psychic
720   Volcanion     Fire

[721 rows x 2 columns]

In [88]:
data.tail(10)

Pokemon     Type
711   Bergmite      Ice
712    Avalugg      Ice
713     Noibat   Flying
714    Noivern   Flying
715    Xerneas    Fairy
716    Yveltal     Dark
717    Zygarde   Dragon
718    Diancie     Rock
719      Hoopa  Psychic
720  Volcanion     Fire

In [89]:
data.index

RangeIndex(start=0, stop=721, step=1)

In [90]:
data.shape

(721, 2)

In [91]:
data.size

1442

In [92]:
data[50:100]

Pokemon      Type
50     Dugtrio    Ground
51      Meowth    Normal
52     Persian    Normal
53     Psyduck     Water
54     Golduck     Water
55      Mankey  Fighting
56    Primeape  Fighting
57   Growlithe      Fire
58    Arcanine      Fire
59     Poliwag     Water
60   Poliwhirl     Water
61   Poliwrath     Water
62        Abra   Psychic
63     Kadabra   Psychic
64    Alakazam   Psychic
65      Machop  Fighting
66     Machoke  Fighting
67     Machamp  Fighting
68  Bellsprout     Grass
69  Weepinbell     Grass
70  Victreebel     Grass
71   Tentacool     Water
72  Tentacruel     Water
73     Geodude      Rock
74    Graveler      Rock
75       Golem      Rock
76      Ponyta      Fire
77    Rapidash      Fire
78    Slowpoke     Water
79     Slowbro     Water
80   Magnemite  Electric
81    Magneton  Electric
82  Farfetch'd    Normal
83       Doduo    Normal
84      Dodrio    Normal
85        Seel     Water
86     Dewgong     Water
87      Grimer    Poison
88         Muk    Poison
89    Shellder     Water
90    Cloyster     Water
91      Gastly     Ghost
92     Haunter     Ghost
93      Gengar     Ghost
94        Onix      Rock
95     Drowzee   Psychic
96       Hypno   Psychic
97      Krabby     Water
98     Kingler     Water
99     Voltorb  Electric

In [95]:
data[-30:]

Pokemon      Type
691   Clauncher     Water
692   Clawitzer     Water
693  Helioptile  Electric
694   Heliolisk  Electric
695      Tyrunt      Rock
696   Tyrantrum      Rock
697      Amaura      Rock
698     Aurorus      Rock
699     Sylveon     Fairy
700    Hawlucha  Fighting
701     Dedenne  Electric
702     Carbink      Rock
703       Goomy    Dragon
704     Sliggoo    Dragon
705      Goodra    Dragon
706      Klefki     Steel
707    Phantump     Ghost
708   Trevenant     Ghost
709   Pumpkaboo     Ghost
710   Gourgeist     Ghost
711    Bergmite       Ice
712     Avalugg       Ice
713      Noibat    Flying
714     Noivern    Flying
715     Xerneas     Fairy
716     Yveltal      Dark
717     Zygarde    Dragon
718     Diancie      Rock
719       Hoopa   Psychic
720   Volcanion      Fire

In [98]:
len(data)

721

In [99]:
data["Year"] = "Null"

In [100]:
data.head()

Pokemon   Type  Year
0   Bulbasaur  Grass  Null
1     Ivysaur  Grass  Null
2    Venusaur  Grass  Null
3  Charmander   Fire  Null
4  Charmeleon   Fire  Null

In [101]:
data.head()

Pokemon   Type  Year
0   Bulbasaur  Grass  Null
1     Ivysaur  Grass  Null
2    Venusaur  Grass  Null
3  Charmander   Fire  Null
4  Charmeleon   Fire  Null

In [104]:
data.insert(1,column="Name", value="Munna")
data.head()

Pokemon   Name Director   Type  Year
0   Bulbasaur  Munna    Munna  Grass  Null
1     Ivysaur  Munna    Munna  Grass  Null
2    Venusaur  Munna    Munna  Grass  Null
3  Charmander  Munna    Munna   Fire  Null
4  Charmeleon  Munna    Munna   Fire  Null